### ISSUE TITLE
class-based views

### ISSUE THREAD

**Issue by jsocol** [jsocol/django-jsonview#18]
Handle the case where the first argument isn't a request!

**Comment by dahoste** [comment]
Yes please.

**Comment by dahoste** [comment]
Meanwhile, I used the following stunt:

```python
from django.contrib.auth.decorators import login_required
from jsonview.decorators import json_view

@classonlymethod
    def as_view(cls, **initkwargs):
        func = super(FancyJSONViewClass, cls).as_view(**initkwargs)
        return login_required(json_view(func))
```


I threw 'login_required' in there, too, just to show you can wrap decorators manually.

So, obviously, this leverages the fact that all CBVs offer themselves up as view functions to Django's URL dispatcher, via their as_view(), which returns a function that looks (not accidentally) just like any old classic view func, and thus exactly meets the signature that json_view's decorator is expecting.

If this holds up, I think I'll convert it into a tiny little mixin for my CBVs.

**Comment by iamahuman** [comment]
Decorators are **NOT** supposed to handle *that* case. Use `@method_decorator(name_of_decorator)` on `dispatch` method instead.

**Comment by iamahuman** [comment]
...and `method_decorator` is the **standard** way to decorate class-based views used even in tutorials, like `@method_decorator(csrf_protect)`

**Comment by jsocol** [comment]
Wrapping the output of `as_view` is [in the docs as a recommended solution](https://docs.djangoproject.com/en/1.8/topics/class-based-views/intro/#decorating-in-urlconf). I think rather than implementing a mixin for CBVs, the correct solution here is documentation and pointing to those Django docs.

**Comment by jsocol** [comment]
Fixed by #25. I'm not going to cut a new release because there were no necessary code changes, just new tests to ensure it keeps working.

**Comment by iamahuman** [comment]
Well, check out the immediate next section of your link, which explains how
to use `method_decorator` :P

**Comment by jsocol** [comment]
Yes, my point was that they are both supported/documented. 



--

**Comment by iamahuman** [comment]
Indeed.
