### ISSUE TITLE
Support for atomic requests

### ISSUE THREAD

**Issue by cameel** [jsocol/django-jsonview#20]
The `json_view()` decorator catches all exceptions which means that with [`ATOMIC_REQUESTS = True`](https://docs.djangoproject.com/en/dev/ref/settings/#std:setting-DATABASE-ATOMIC_REQUESTS) exceptions do not cause a rollback.

It's easy to work around by explicitly putting `@transaction.atomic` decorator on a view below `@json_view` but it's a gotcha and also easy to forget. I think that `json_view()` should be doing the same thing Django does to get the rollback behavior of normal views (I'm not sure if it's just this decorator or a bit more magic). Or at least document the current behavior in the README.

**Comment by jsocol** [comment]
Hmm, I mostly agree, I'm just not really sure how to do it. At the very least, it makes sense to add a note about `@transaction.atomic` to the docs.

**Comment by cameel** [comment]
Well, I've just looked at Django source and it has a method called [`BaseHandler.make_view_atomic()`](https://github.com/django/django/blob/0ed7d155635da9f79d4dd67e4889087d3673c6da/django/core/handlers/base.py#L76-L82). It simply applies `transaction.atomic()` (or not) for all database connections based on the value of `ATOMIC_REQUESTS` and a view property called `_non_atomic_requests`. The method is self-contained (does not even use `self`) but it's undocumented.

It [gets called on a view by `BaseHandler.get_response()`](https://github.com/django/django/blob/0ed7d155635da9f79d4dd67e4889087d3673c6da/django/core/handlers/base.py#L130) just before it executes the view itself.

So I'd create a `BaseHandler` instance ([the constructor](https://github.com/django/django/blob/0ed7d155635da9f79d4dd67e4889087d3673c6da/django/core/handlers/base.py#L30-L35) is pretty lightweight) and call the method or just copy the condition and apply `@transaction.atomic()`. I see both downsides and upsides for either of these options: condition may change in future versions of Django (though `git blame` shows that it hasn't changed since its introduction in 1.6) but the method is undocumented and can also be removed or altered in the future. I'd personally go with calling the method because if it gets removed or its signature changes and the call fails, breakage will be easily noticed and fixed.

The only potential problem is compatibility with pre-1.6 versions of Django. The logic would have to be conditional to account for that (before 1.6 atomic requests were the default behavior and the transaction API was different). Or you could simply state in README that this only works in Django 1.6 and later and earlier versions require a transaction decorator (whatever it was called in earlier versions).
