### ISSUE TITLE
"Using json JSON module." on module import?

### ISSUE THREAD

**Issue by Bartvds** [jsocol/django-jsonview#27]
We use a lot of management commands in cronjobs and such, some of which run quite often. So as a rule we don't log unless it is actually valuable information, or else our logs get swamped.

But this module prints a "Using json JSON module." line on every initialization :confused:

I'm not quite sure why printing this line is necessary; not many modules we've used repeat back their settings on every app invocation.

If you must have this visible then maybe it should be put behind the DEBUG flag?

**Comment by jsocol** [comment]
Agreed. This *could* use a different logger—everything else needs to stick with `django.request`, though—but it definitely needs to be `.debug()` and not `.info()`.

**Comment by jsocol** [comment]
Fixed in master
